CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY  ,
    email varchar NOT NULL UNIQUE,
    "password" varchar NOT NULL
);

CREATE TABLE passengers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    first_name varchar NOT NULL,
    last_name varchar NOT NULL,
    data_birth DATE NOT NULL,
    gender varchar NOT NULL,
    photo varchar NOT NULL,
    user_id BIGSERIAL REFERENCES users(id) ON DELETE CASCADE
);